.eslintrc.cjs, package-lock.json, package.json, src/App.tsx, src/Assets/Fonts/Fonts.css, src/Styles/Global.ts
-
모든 컴포넌트에게 기본으로 적용되는 스타일들을 초기화하고 폰트를 적용하였습니다. 추가로 설치한 라이브러리가 있으니, pull 이후 `npm install`을 통해 설치해주세요.
-
1. approve 이전에 조절할 수치들이나, 추가적으로 적용해야될 것들 함께 얘기해보면 좋을 듯 합니다.
2. App 컴포넌트 화살표 함수로 바꾸고 깃헙에서 충돌처리 하니 로그가 하나 생겼네요 (0076cb901b47497469939f152087df1cd4e00725)
3. [font-family](https://github.com/prgrms-fe-devcourse/FEDC5_STYLED_sehee/pull/1/files#diff-e7c9cb6605fd4e067a96294133b7721716a1642343b82f9204c344f536d945baR25)는 웹 호환성을 고려하여 [제작자](https://github.com/orioncactus/pretendard?tab=readme-ov-file#font-family)가 권장하는 구성을 사용하였습니다.
=> Style: 전역 스타일 설정

src/Hooks/UseForm/Type.ts, src/Hooks/UseForm/index.ts, src/Hooks/index.ts
`feature/useFormHook` -> `dev`
모든 form 태그에서 input 데이터 바인딩, 유효성 검사, submit 콜백 함수를 사용할 수 있는 useForm 커스텀 훅 기능 개발
- 재사용성 위주로 작성해봤는데 타입이 잘 처리되었는지 다른 분 생각이 궁금합니다.
=> Feat: useForm 커스텀 훅 기능 개발

src/Components/Common/Modal/index.tsx, src/Components/Common/Modal/style.ts, src/Components/Common/Modal/type.ts
`feature/modalComponent` -> `dev`
Common 재사용 가능한 Modal 컴포넌트를 구현했습니다.
> 피드백 반영
- 타입과 스타일 컴포넌트 분리가 제대로 이루어진 건지 봐주세요!
- 원래는 외부 버튼에 대한 ref를 가져와서 이벤트를 설정하려고 했으나 ref가 계속 `null`값으로 받아와져서 포기했어요...
- 대신 모달 선언하는 컴포넌트에서 `isOpen` 상태와 모달을 여는 버튼 컴포넌트를 추가하여 연결만 하면 가능하도록 구현했습니다.
=> Feat: Common Modal 컴포넌트 구현

src/App.tsx, src/Components/Base/Button/index.tsx, src/Components/Base/Button/style.ts, src/Components/Base/Button/type.ts, src/Styles/Theme.ts
`feature/buttonComponent` -> `dev`
1. `버튼` 공용 컴포넌트입니다. 색상과 크기, 테두리 둥근 정도를 필수로 전달받고 토글버튼 여부와 콜백함수들을 선택적으로 전달받습니다.
2. 색상(color)과 테두리 둥근 정도(borderRound)는 문자열 형태로 입력받아 프리셋을 통해 부여되도록 구현하였습니다.
> 피드백 반영
- 입력 파라미터 관련 개선사항이 있을까요?
- `width`, `height`를 필수 프롭으로 전달받아야 할까요?
- `width`, `height`, `border-radius`에도 반응형 단위가 부여되도록 구현하는게 맞을까요? (테두리가 "`extra-small`rem" 일 때도 너무 둥글어요..ㅜ)
- 토글 버튼일 경우 `isActive` 상태를 통해 토글 여부를 관리하고, `onActiveChange` 콜백을 통해 현재 토글 상태를 상위 컴포넌트에게 전달하는 방식으로 구현해보았는데 보시고 피드백 부탁드립니다.
- 전역 `defaultTheme`의 색상이 다소 한정적이라 `Hover` 효과 구현을 보류하였습니다. 사용되는 색상들이 밝기? 상황?별로 구현된 색상표를 객체 형태로 관리하면 좋을 것 같아요~~
=> Feat: Button 컴포넌트 추가

src/App.tsx, src/Components/Base/Input/index.tsx, src/Components/Base/Input/style.ts, src/Components/Base/Input/type.ts
`feature/inputComponent` -> `dev`
input 컴포넌트에서 에러 메세지를 받아 UI에 보여주는 기능을 추가
props에 errorMesasge가 추가되고 선택적으로 받을 수 있습니다. 일단 색상과 사이즈를 고정으로 설정했습니다.
- form 작업하면서 input 컴포넌트 내부에서 한 번에 처리하면 좋을 것 같다고 생각해서 추가했는데 다들 괜찮으실까요?
=> Feat: Input 컴포넌트 에러 메세지 출력 기능 추가

src/Components/Base/Button/index.tsx, src/Components/Base/Button/type.ts
`feature/fixButtonComponent` -> `dev`
Button 공용 컴포넌트에서 ref와 클릭이벤트 관련 props 로직 및 타입을 수정했습니다.
- 추후에 ref나 토글이벤트가 문제 있을 경우 문의주세요!
- Button 컴포넌트 테스트 코드입니다. (Pages/Homepage/index.tsx)
```js
import { Link } from 'react-router-dom';
import { useEffect, useRef } from 'react';
import Button from '@/Components/Base/Button';
const HomePage = () => {
const btnRef = useRef<HTMLButtonElement>(null);
useEffect(() => {
console.log(btnRef.current);
}, [btnRef]);
return (
<>
<div>HomePage</div>
<Link to="/detail">Detail</Link>
<Button
ref={btnRef}
onClick={() => console.log('클릭')}
>
가져오기
</Button>
</>
);
};
export default HomePage;
```
=> Fix: Button 컴포넌트 ref 및 클릭이벤트 props 수정

src/Components/Base/Input/index.tsx, src/Components/Base/Input/type.ts
`feature/InputComponentRef` -> `dev`
- forwardRef를 사용해 상위 컴포넌트에서 input 태그를 ref로 참조할 수 있게 기능을 추가했습니다.
=> Feat: Input 컴포넌트 ref 기능 추가

src/Hooks/UseClickAway/index.ts, src/Hooks/index.ts
`feature/useClickAway` -> `dev`
지정한 컴포넌트의 바깥을 클릭하면 지정한 핸들러 함수가 실행 되도록 하는 커스텀 훅 입니다.
```jsx
const [isShow, setIsShow] = useState(false);
// 바깥을 클릭했을 때 실행될 함수를 전달한다.
const ref = useClickAway(() => {
setIsShow(false);
};);
...
<button 
ref={ref} 
onClick={()=>setIsShow(true)}
>테스트 버튼</button>
{isShow && <div>보이나요?</div>}
```
이런식으로 사용하시면 됩니다.
- 타입스크립트 관련 고민을 많이 하며 만들었는데(너무 빨간줄이 많이 나서...), 그냥 useRef에는 타입을 지정하지 않고, useEffect 내부에서 `타입 단언` 과 `타입 가드` 를 통해 구현하게 되었습니다. `useRef<HTMLElement>` 로 지정하니 Legacy, Mutable 이런 세세한 속성까지 맞지 않는다고 자꾸 뭐라 하네요.😭 `useRef<HTMLButtonElement>` 이런식으로 세세하게 지정해주면 오히려 오류는 안나는데, 그러면 재사용에 문제가 생겨서 그냥 useRef에는 타입을 지정하지 않게 되었습니다!
- 그리고 useEffect return 에는 화살표 함수를 사용해야하는데 eslint에서 막아서 이 부분 주석 처리 했습니다. 
- 기타 궁금하신 점 있으시면 질문 주세요!
=> Feat: useClickAway 커스텀 훅 기능 개발

src/Components/Common/PostCard/index.tsx, src/Components/Common/PostCard/style.ts, src/Components/Common/PostCard/type.ts
`feature/postCard` -> `dev`
메인 화면에 나타날 포스트 카드를 구현
- 포스트 카드의 크기를 width를 props로 넘겨주게 하고 비율을 1대1 정방형으로 되게 일단 만들었습니다. 크기 조정에 대한 다른 좋은 아이디어가 있다면 알려주세요.
- 아직 Icon과 Button 컴포넌트와 같은 공용 컴포넌트가 완성이 되지 않아 styled 컴포넌트로 대체했습니다. 이후 추가 리팩토링이 필요해보입니다.
=> Feat: PostCard 공용 컴포넌트 구현

src/Components/Common/ImageUpload/index.tsx, src/Components/Common/ImageUpload/style.ts, src/Components/Common/ImageUpload/type.ts, src/Pages/HomePage/index.tsx
`feature/imageUpload` -> `dev`
사진을 업로드할 수 있는 공용 컴포넌트를 구현했습니다.
- 추가적으로 props로 넘겨줄 만한 것이 있다면 알려주세요!
=> Feat: ImageUpload 컴포넌트 구현

src/App.tsx, src/Stores/DarkMode/index.ts, src/Stores/DarkMode/type.ts, src/Stores/index.ts
`feature/darkMode` -> `dev`
다크모드 상태를 전역 상태 관리로 관리하며 현재 다크모드 여부에 따른 Theme 객체를 적용
=> Feat: 다크모드 전역 상태 관리 기능 추가

src/App.tsx, src/Components/Base/Avatar/index.tsx, src/Components/Base/Avatar/style.ts, src/Components/Base/Avatar/type.ts, src/Components/Base/Badge/index.tsx, src/Components/Base/Badge/style.ts, src/Components/Base/Badge/type.ts
`feature/badgeComponent` -> `dev`
알림, 접속 중임을 알리는 Badge 컴포넌트입니다.
1. 부착을 원하는 요소에 children을 통해 Badge 컴포넌트를 내려주시고, `position: relative`로 설정해주세요.
2. `children`을 내려주지 않거나, 한 글자인 경우 원형을 유지하도록 하였습니다. 이외의 경우에는 내려주는 children에 따라 크기가 확장됩니다.
3. 99개 이상의 알림이 오는 경우 99+로 고정하여 출력하도록 하였습니다.
4. Badge의 `position`은 각 모서리 4방향을 `'leftTop'` | `'leftBottom'` | `'rightTop'` | `'rightBottom'` 프롭으로 지정 가능하게 하였습니다. 기본값은 `'rightTop'`입니다.
- 타입, 스타일 컴포넌트, index 구현
- Avatar 컴포넌트 wrapper 추가, 내부 컴포넌트에 크기를 상속하도록 함 
- Prop과 초기값, 단위 관련하여 개선사항이 있다면 피드백 주시면 감사하겠습니다.
- Badge 컴포넌트와의 호환을 위하여 Avatar 컴포넌트도 수정하였으니, 참고 부탁드립니다. (wrapper, 크기 상속 등)
=> Feat: Badge 컴포넌트 구현

src/App.tsx, src/Components/Common/DropDown/index.tsx, src/Components/Common/DropDown/style.ts, src/Components/Common/DropDown/type.ts, src/Styles/Theme.ts
`feature/dropDownComponent` -> `dev`
(`drop-shadow`는 차이가 있습니다.)
1. `options=[]` 프롭을 통해 데이터를 렌더링하는 드롭다운 컴포넌트입니다.
2. 배경색, 글씨색, 글씨크기 등의 자주 사용되는 프롭들을 선택적으로 넘겨줄 수 있으며, 요소마다 부착된 {...elementProp}으로 부가적인 프롭을 전달할 수 있습니다.
3. 내부에서 현재 선택된 옵션을 State로 관리하며, 기본값은 `'선택 없음'`입니다. 이 경우 우측 버튼이 하단화살표 모양을 띄고, 클릭 시 드롭다운이 토글됩니다.
4. 유효한 옵션이 선택된 상태일 경우 우측 버튼은 취소 모양을 띄고, 클릭 시 '선택 없음' 옵션으로 초기화되고, 드롭다운이 닫히게 됩니다.
> 피드백 반영
- 기존에 부여했던 스타일 단위들을 반응형(rem)으로 수정하였습니다.
1. 프롭, 로직, 확장성 등등 관련하여 피드백 부탁드립니다.
=> Feat: DropDown 컴포넌트 구현

src/Components/Common/Modal/style.ts
`feature/fixModal` -> `dev`
모달이 아래쪽으로 치우치는 버그를 수정하기 위해 모달의 wrapper이 너비와 높이를 100vw, 100vh에서 부모요소의 100%로 변경했습니다.
- 다른 예외적이 에러 있으면 언제든지 말씀해주세요!
[Feat: Common Modal 컴포넌트 구현 #9](https://github.com/prgrms-fe-devcourse/FEDC5_STYLED_sehee/pull/9)
=> Fix: Modal 컴포넌트 wrapper 너비 및 높이 수정

src/Api/interceptors.ts, src/Components/Common/HistoryBackButton/index.tsx, src/Components/Common/Logo/index.tsx, src/Components/Login/LoginForm/index.tsx, src/Components/Login/LoginForm/type.ts, src/Components/Login/MoveToSignUpButton/index.tsx, src/Hooks/UseForm/index.ts, src/Hooks/UseForm/type.ts, src/Pages/LoginPage/index.tsx, src/Stores/AuthUser/index.ts, src/Stores/AuthUser/type.ts, src/Stores/DarkMode/index.ts, src/Styles/Theme.ts
`feature/login` -> `dev`
로그인 기능 개발
로그인 성공 시
- 로그인 전역 상태 추가
- 세션 스토리지 token 추가
- 메인 페이지로 이동
로그인 실패 시
- Alert 컴포넌트 모달 제공
인증 상태에서 로그인 페이지 진입 시
- 세션 스토리지 토큰을 이용해 인증 되었는지 확인
- 인증 되었다면 유저 정보를 전역 상태에 담는다.
- 인증 되었다면 메인 페이지로 이동
Alert 모달을 띄우긴 했는데 다크모드 시 적용할 부분이 좀 있는 것 같습니다! 추가적으로 폰트 크기도 조절할 수 있으면 좋겠어요!
=> Feat: 로그인 기능 개발

src/Components/Common/UserCard/index.tsx, src/Components/Common/UserCard/style.ts, src/Components/Common/UserCard/type.ts
`feature/userCard` -> `dev`
채팅 유저나 유저 목록 등에 사용될 수 있는 UserCard를 구현했습니다.
- onClick 이벤트에 대한 처리를 잘 못하겠네요.. 어디부터 해야할지 감이 안 잡혀요.. 사용하시면서 수정할 부분을 알려주시면 좋을 거 같아요!
=> Feat: UserCard 공용 컴포넌트 구현

src/Components/Common/Alert/index.tsx, src/Components/Common/Alert/style.ts, src/Components/Common/Alert/type.ts
`feature/fixAlert` -> `dev`
- Alert 컴포넌트의 메세지 크기를 조절할 수 있는 `fontSize` props를 추가했습니다.
- 단위는 rem입니다.
.
=> Feat: Alert 컴포넌트 메세지 크기 props 추가

src/Components/Common/Modal/index.tsx, src/Components/Common/Modal/style.ts, src/Components/Common/Modal/type.ts
`feature/fixModal3` -> `dev`
- Modal에 다크모드를 위한 옵션을 추가했습니다.
- 다크모드 적용시 border, text는 white, background는 black 적용했습니다.
- light모드일 경우에도 border: white로 두었는데 문제 없겠죠..?
=> Feat: Modal 다크모드 props 추가

src/Components/Common/DropDown/index.tsx, src/Components/Common/DropDown/style.ts, src/Components/Common/DropDown/type.ts
`feature/` -> `dev`
드롭다운 컴포넌트를 리팩토링하였습니다.
1. 기본 디자인을 사용하고자 하는 경우
```
<DropDown options={['1', '2', '3']} />
```
2. children과 inline-styling을 통한 커스텀 디자인
```
<DropDown
options={['1', '2', '3']}
buttonProps={{
style: {
justifyContent: 'center',
border: 'none',
},
}}
>
<Icon name="account_circle" />
</DropDown>
```
=> Refactor: DropDown 컴포넌트 리팩토링

package-lock.json, package.json, src/App.tsx, src/Components/UserManager/UserItem/index.tsx, src/Components/UserManager/UserItem/style.ts, src/Components/UserManager/UserItem/type.ts, src/Components/UserManager/UserList/index.tsx, src/Components/UserManager/UserList/style.ts, src/Components/UserManager/UserList/type.ts, src/Components/UserManager/UserSearchForm/index.tsx, src/Components/UserManager/index.tsx, src/Components/UserManager/style.ts, src/Constants/queryKeys.ts, src/Pages/HomePage/index.tsx, src/Pages/HomePage/style.ts
`feature/getUserList` -> `dev`
limit, offset을 상태로 관리하여 사용자 목록을 불러와 실제로 보여질 상태 배열에 지속적으로 저장
옵저버 라이브러리를 이용하여 limit, offset을 10씩 증가
실시간 사용자 목록을 2초 간격마다 불러와서 현재 보여질 사용자 목록을 비교
- SearchBar 컴포넌트 위치 조정이 좀 잘 안돼서 일단 조회부터 진행했습니다. SearchBar 수정되면 검색 구현 마무리 하겠습니다.
- 스크롤 바 색을 일단 검정색으로 했는데 먼가 마음에 들진 않네요,,
=> Feat: 전체 사용자 목록 조회

src/Pages/HomePage/index.tsx, src/Pages/HomePage/style.ts, src/Utils/checkSuperUser.ts
`feature/mainPagePostScroll` -> `dev`
메인 페이지 채널 클릭 시 포스트의 무한 스크롤을 구했습니다.
- 메인페이지에서 로그인 안했을 경우 로그인 확인 창 보이도록 대략적으로 해볼려고 했는데 잘 안되네요...
그냥 기존 하기로 했던 것처럼 메인페이지에서 인증된 사용자만 수행할 수 있는 기능을 실행하려고 하면 로그인 권유 및 로그인 창으로 이동하는 방식으로 구현하는 것이 맞을 거 같습니다.
=> Feat: 메인 페이지 포스트 무한 스크롤 구현

src/Components/Common/UserCard/index.tsx, src/Components/DirectMessage/ConversationList/index.tsx, src/Components/DirectMessage/ConversationList/style.ts, src/Hooks/useResize/index.ts, src/Pages/DetailPage/PostDetailModal/index.tsx, src/Pages/DirectMessagePage/index.tsx
`feature/fixDirectAndUserCardClick` -> `dev`
User Card 내 닉네임과 아바타 클릭 이벤트에 대한 오류를 해결하고
포스트 상세페이지에서 다이렉트 메시지 페이지로 넘어갈 때 receiver가 유지 안되는 버그를 해결했습니다.
- 추가 에러 사항은 현주님이 추가 PR할 예정입니다.
=> Fix: User Card 이름 및 아바타 클릭 오류 및 다이렉트 메시지 버그 수정

src/Components/Common/Header/HeaderTab/LoginButton/index.tsx, src/Components/Common/Header/HeaderTab/index.tsx
`feature/fixLoginPageBackButton` -> `dev`
로그인 페이지 뒤로가기 버튼 클릭 시 2번 클릭해야 동작하는 버그 수정했습니다.
히스토리에 로그인 페이지 이동이 2번 동작
=> Fix: 로그인 페이지 뒤로가기 버튼 2번 클릭 시 이동하는 버그 수정

src/Components/DarkMode/style.ts
`feature/designDarkModeButton` -> `dev`
다크 모드 버튼 왼쪽으로 이동했습니다.
=> Design: 다크 모드 버튼 왼쪽으로 이동

src/Components/Common/UserCard/index.tsx, src/Components/Common/UserCard/style.ts, src/Components/Common/UserCard/type.ts, src/Components/DirectMessage/ConversationList/index.tsx, src/Components/DirectMessage/ConversationList/type.ts, src/Components/DirectMessage/MessageList/index.tsx, src/Components/DirectMessage/MessageList/style.ts, src/Components/DirectMessage/MessageList/type.ts, src/Components/DirectMessage/MessageModal/index.tsx, src/Components/DirectMessage/MessageModal/type.ts, src/Components/DirectMessage/Skeleton/index.tsx, src/Components/DirectMessage/Skeleton/style.ts, src/Components/NotificationModal/NotificationItem/index.tsx, src/Components/Profile/ProfileInfo/UserProfileInfo/index.tsx, src/Hooks/Api/Message/index.ts, src/Hooks/Api/Notification/index.ts, src/Pages/DetailPage/PostDetailModal/index.tsx, src/Pages/DirectMessagePage/index.tsx, src/Stores/MessageReceiver/index.ts, src/Stores/MessageReceiver/type.ts
`feature/RefactorDirectMessage3` -> `dev`
- 스켈레톤은 처음 로딩될 때만 길게 적용, 이후 짧게 적용됩니다.
- 실시간 대화가 가능하도록 conversations, messages를 2초에 한번씩 불러오도록 `refetchInterval` 옵션을 주었습니다.
- 상대방과의 채팅방이 켜져있고, messages가 refetch될 때 알림도 같이 읽도록 적용했습니다.
- 글쓰기 버튼 hover시 검은색 배경이 생기던 현상을 수정했습니다.
- isClickedUserCard 상태를 전역 스토어로 분리했습니다.
- 코드를 정리했습니다. 기존에 자식에게 Props로 전달하던 것들을 해당 자식 컴포넌트에서 직접 스토어에서 꺼내서 사용하는 방식으로 변경했습니다.
.
=> Refactor: 다이렉트 메세지 페이지 QA 수정사항 반영

src/Services/Channel/index.ts
`feature/createChannelEncoding` -> `dev`
getChannel 함수 내부에서 만약 채널명이 한글인 경우, 인코딩 작업을 거친 뒤 API를 호출하도록 수정했습니다.
- 테스트 해봤는데 채널 정보가 잘 내려옵니다!
- 그런데 테스트 해본 결과 인코딩 안해도 잘 오는 것 같습니다....😮 그래도 요구사항이니 혹시 몰라서 인코딩 작업 추가했습니다!
=> Refactor: getChannel API 함수 내부에서 채널 이름이 한글인 경우 인코딩 작업 추가

src/Components/Common/Modal/AddOrEditPostModal/AsideHeader/index.tsx
`feature/fixAddPost` -> `dev`
포스트 추가 모달에서 채널 드롭다운이 연동되지 않는 문제를 해결했습니다.
- 급한 건입니다! approve 해주세요!
=> Fix: 포스트 추가 모달에서 Channel 드롭다운 매핑 문제 해결

src/Components/FollowModal/index.tsx, src/Components/Profile/ProfileInfo/UserProfileInfo/index.tsx
`feature/FixFollowModal2` -> `dev`
- 팔로우 모달, 유저 상세 페이지에서 팔로우 버튼을 연타하는 경우 중복으로 들어가는 현상이 발견되어 debounce로 해결했습니다.
.
=> Fix: 팔로우 연타 시 중복으로 들어가던 현상 debounce로 해결
