src/App.tsx, src/Styles/Animation.ts, src/Styles/Theme.ts, src/Styles/style.d.ts
기능 추가
feature/theme -> dev
theme 객체 데이터를 추가했습니다.
App.tsx파일에 theme 설정 추가
Animation 전역 스타일 파일을 만들었습니다.
=> Feat: theme 데이터 추가

index.html, src/Components/Base/Icon/index.tsx, src/Components/Base/Icon/style.ts, src/Components/Base/Icon/type.ts
`feature/IconComponent` -> `dev`
아이콘 컴포넌트
- 더 필요한 iconProps가 있는지 궁금합니다
.
=> Feat: Icon 컴포넌트

src/Types/CommentType.ts, src/Types/PostType.ts, src/Types/Request/index.ts, src/Types/UserType.ts
`feature/FixType` -> `dev`
이름에 type 누락 수정 및 image type 수정
.
.
=> Fix: 이름에 type 누락 수정 및 image type 수정

src/Components/Common/Modal/index.tsx, src/Components/Common/Modal/style.ts, src/Components/Common/Modal/type.ts
`feature/fixModal` -> `dev`
Modal 컴포넌트 PR 피드백 적용
- 추가 피드백 요소 있으면 알려주세요~
=> Fix: Modal 컴포넌트 PR 피드백 적용

index.html, src/Components/Base/Icon/index.tsx
`feature/fixIcon` -> `dev`
채워진 아이콘 관련 피드백
.
.
=> Fix: 채워진 아이콘 관련 피드백

src/Styles/Theme.ts
`feature/theme` -> `dev`
급하게 필요해서 background 색상을 theme에 추가
- 더 필요한 색상이나 추가 요구사항있으시면 댓글 부탁드립니다!
=> Feat: Theme 색상 추가

index.html, src/Components/Base/Icon/index.tsx, src/Components/Base/Icon/style.ts
`feature/fixIcon` -> `dev`
Icon 컴포넌트 outline관련 피드백 반영
.
.
=> Fix: Icon 컴포넌트 outline관련 피드백 반영

src/App.tsx, src/Components/Common/SearchBar/index.tsx, src/Components/Common/SearchBar/style.tsx, src/Components/Common/SearchBar/type.ts
`feature/SearchBar` -> `dev`
SearchBar 컴포넌트
- SearchBar 컴포넌트 상단 고정 여부 (현재는 고정된 상태 + center)
- 더 필요한 prop이나 개선해야할 점이 있는지 궁금합니다
.
=> Feat: SearchBar 컴포넌트

src/Components/Base/Avatar/index.tsx, src/Components/Base/Avatar/style.ts, src/Components/Base/Avatar/type.ts
`feature/avatarComponent` -> `dev`
유저 프로필 등에 사용되는 아바타 컴포넌트입니다.
> 피드백 반영
- 추가하거나 제거해야할 Props가 있을까요?
- 기타 의견 피드백 주시면 반영하겠습니다~~
=> Feat: Avatar 컴포넌트 추가

src/Components/Base/Button/index.tsx, src/Components/Base/Button/style.ts, src/Components/Base/Button/type.ts
`feature/buttonComponent` -> `dev`
Button 컴포넌트의 피드백을 반영하여 리팩토링하였습니다.
- 검색 결과 Tab 버튼 등에 focus, hover할 경우 text 색상도 변경되는 곳이 있어 함께 추가하였습니다.
[Feat: Button 컴포넌트 추가](https://github.com/prgrms-fe-devcourse/FEDC5_STYLED_sehee/pull/8)
=> Refactor: Button 컴포넌트 코드리뷰 피드백 반영

src/App.tsx
`feature/reactQuery` -> `dev`
Provider로 react-query를 전역적으로 사용할 수 있게 설정했습니다.
- default 옵션을 설정할 수 있는데 일단 요청 실패 시 기본적으로 3번을 더 요청하는 부분을 2번으로 설정했습니다. 더 추가하고 싶은 옵션 있으시면 말씀해주세요!
=> Feat: react query 초기 설정

src/App.tsx, src/Components/Common/Alert/index.tsx, src/Components/Common/Alert/style.ts, src/Components/Common/Alert/type.ts
`feature/Alert` -> `dev`
- 여러 페이지에서 자주 사용되는 Alert 컴포넌트를 만들었습니다.
- `mode` 에 따라서 `alert`, `confirm` 2가지 형태를 지원합니다.
- Alert 바깥을 클릭 시 `cancle` 과 유사하게 동작합니다.
- `Modal` 을 재사용하여 만들었습니다.
```jsx
const [isShow, setIsShow] = useState(false);
...
<button onClick={()=>setIsShow(true)}>게시물 삭제 버튼</button>
{isShow && (
<Alert
onChangeOpen={setIsShow}
message="정말 삭제하시겠습니까?"
mode="confirm"
onConfirm={() => 삭제를 하는 로직 수행}
onCancle={() => 삭제를 하지 않았을 때 로직 수행}
/>
)}
```
```jsx
const [isShow, setIsShow] = useState(false);
...
<button onClick={()=>setIsShow(true)}>게시물 삭제 버튼</button>
{isShow && (
<Alert
onChangeOpen={setIsShow}
message="정말 삭제하시겠습니까?"
// mode="confirm"
onConfirm={() => 삭제를 하는 로직 수행}
// onCancle={() => 삭제를 하지 않았을 때 로직 수행}
/>
)}
```
- 추가적으로 원하시는 기능이나 props 있으시면 말씀해주세요!
=> Feat: Alert 컴포넌트 구현

src/Constants/Channels.ts
`feature/createChannel` -> `dev`
- API 함수를 호출하여 서버에 채널을 생성한 뒤, Constants/Channels에 채널 이름을 `영어 : 한글` 형태로 상수화 시켰습니다.
- 채널은 피그마 설계 당시 계획대로 생성했습니다.
- `캐주얼` `스트릿` `아메카지` `시크` `댄디` `걸리시` `홈웨어` `스포티` `고프코어`
.
=> Feat: 채널 생성 및 상수화

src/Components/Base/Spinner/index.tsx, src/Components/Base/Spinner/style.ts, src/Components/Base/Spinner/type.ts, src/Styles/Animation.ts
`feature/spinnerComponent` -> `dev`
1. 로딩 중임을 나타내는 spinner입니다. `size(number)`, `color(string)`, `display(string)`를 변경할 수 있습니다.
2. display의 기본값은 `inline-block`입니다.
3. `isFixedSpinner` 프롭을 통해 스피너를 화면 정중앙에 고정시킬 수 있습니다.
4. `isBackground` 프롭을 통해 스피너가 출력될 때 어두운 배경을 포함시킬 수 있습니다.
- inline-block (default)
- isFixedCenter + isBackground
- 피드백 부탁드립니다~!
=> Feat: Spinner 컴포넌트 구현

src/Hooks/UseSessionStorage/index.ts, src/Hooks/index.ts
`feature/useSessionStorage` -> `dev`
- 세션스토리지 커스텀 훅 기능 개발
- 사용하실 때 제너릭 타입을 이용하시면 됩니다!
=> Feat: 세션스토리지 커스텀 훅 기능 추가

src/Components/Common/Modal/index.tsx, src/Components/Common/Modal/style.ts, src/Components/Common/Modal/type.ts
`feature/fixModal2` -> `dev`
Modal 컴포넌트 렌더링 포탈 및 props 일부 수정
- 추가 수정사항 있으면 언제든지 알려주세요~
[Feat: Common Modal 컴포넌트 구현 #9](https://github.com/prgrms-fe-devcourse/FEDC5_STYLED_sehee/pull/9)
=> Fix: Modal 컴포넌트 렌더링 포탈 및 props 일부 수정

src/Components/Login/LoginForm/index.tsx, src/Components/Login/LoginForm/validateLogin.ts, src/Hooks/UseForm/index.ts
`feature/fixLoginForm` -> `dev`
로그인 폼 텍스트 왼쪽으로 정렬 수정
폼 입력받을때 마다 유효성 검사하도록 수정
=> Fix: fixLoginForm

src/Components/Base/Icon/index.tsx, src/Components/Base/Icon/type.ts
`fix/fixIcon` -> `dev`
icon 클래스 추가
.
.
=> Fix: icon 클래스 추가

src/Constants/storage.ts, src/Stores/DarkMode/index.ts
`feature/darkModeStorage` -> `dev`
Theme 모드를 새로고침 해도 유지되게 세션 스토리지에 연결했습니다.
=> Feat: Theme 모드 세션스토리지 저장

src/Components/Common/Header/HeaderTab/LinkButton/index.tsx, src/Components/Common/Header/HeaderTab/ModalButton/index.tsx, src/Components/Common/Header/style.ts
`feature/fixHeader` -> `dev`
- Header에 가려지는 이슈 해결
- Header 아래 border 추가
.
=> Fix: Header에 가려지는 이슈 해결

src/Components/Common/PostCard/index.tsx, src/Components/Common/PostCard/type.ts, src/Constants/queryKeys.ts, src/Pages/DetailPage/PostDetailModal/index.tsx, src/Pages/DetailPage/index.tsx, src/Pages/HomePage/index.tsx, src/Routes/Router.tsx
`feature/mainPageLike` -> `dev`
메인 페이지 및 포스트 상세 페이지 좋아요 기능 api 연결 및 구현하였습니다.
추가 세부 수정 사항도 있습니다.
=> Feat: 메인 페이지 및 상세 페이지 좋아요 기능 구현 및 세부 추가 수정사항 수정

src/App.tsx, src/Components/DarkMode/index.tsx, src/Components/DarkMode/style.ts, src/Components/DarkMode/type.ts, src/Components/UserManager/UserItem/style.ts, src/Components/UserManager/index.tsx, src/Styles/Animation.ts, src/Styles/Global.ts
`feature/darkMode` -> `dev`
다크 모드 버튼 구현했습니다.
- 위치 괜찮나요...?
=> Feat: 다크 모드 기능 버튼 구현

src/Components/NotificationModal/NotificationItem/index.tsx
`feature/fixNotification` -> `dev`
간단한 경로 오류입니다^>ㅎ!
=> Fix: MessageReceiver 모듈 경로 수정

src/Components/DirectMessage/ConversationList/index.tsx, src/Components/DirectMessage/MessageModal/index.tsx, src/Components/NotificationModal/NotificationItem/index.tsx, src/Constants/queryKeys.ts, src/Hooks/Api/Message/index.ts, src/Hooks/Api/Search/index.ts, src/Pages/DetailPage/PostDetailModal/index.tsx
`feature/RefactorDirectMessage` -> `dev`
- 리액트 쿼리를 커스텀 훅으로 분리했습니다.
- 다른 페이지에서 디엠 페이지로 넘어올 때 해당 유저에게 온 메세지를 알림을 읽도록 기능을 추가했습니다.
.
=> Refactor: 다이렉트 메세지 리액트 쿼리 커스텀 훅 분리 및 읽기 기능 추가

.github/workflows/main.yml
`feature/githubVercelSetting` -> `dev`
깃허브와 vercel 자동 연동을 위한 main.yml 파일입니다.
=> Chore: Create main.yml

src/Components/Common/Header/HeaderTab/index.tsx, src/Components/NotificationModal/CategoryItem/style.ts, src/Components/NotificationModal/CategoryList/style.ts, src/Components/NotificationModal/filterNotification.ts, src/Components/NotificationModal/index.tsx, src/Components/NotificationModal/style.ts, src/Hooks/UseClickAway/index.ts, src/Styles/Animation.ts
`feature/fixNotification` -> `dev`
1. 알림 창 외부 영역 클릭 시 알림 창 닫기 기능 추가
2. 알림 창 반응형 디자인 
3. 자기 자신 좋아요 알림 제거
4. 알림 아이콘 클릭은 알림을 보여주는 역할만하고 닫히는 건 막았습니다. 
5. 슬라이드 인, 아웃 효과 애니메이션 추가했습니다.
=> Fix: 알림 기능 수정

src/Components/UserManager/index.tsx
`feature/UserManagerLoading` -> `dev`
유저 관리 컴포넌트 스켈레톤 UI 적용했습니다.
=> Fix: 유저 관리 컴포넌트 스켈레톤 UI 적용

src/Components/Common/ImageUpload/index.tsx, src/Components/Common/Modal/AddOrEditPostModal/index.tsx, src/Pages/AddOrEditPostPage/index.tsx
`feature/AddOrEditPage(fix)` -> `dev`
=> Fix: 포스트 작성, 수정 관련 이슈들

src/Components/Common/Header/HeaderLogo/index.tsx, src/Pages/HomePage/index.tsx, src/Pages/HomePage/style.ts, src/Styles/Global.ts
`feature/mainCategroyResponsive` -> `dev`
모바일 화면에서 카테고리 채널을 선택할 수 있는 드롭다운을 구현했습니다.
- 크기나 디자인이 적당한지 피드백 주세요
=> Design: 모바일 카테고리 드롭다운 구현

src/Components/FollowModal/style.ts
`feature/fixWhiteDot` -> `dev`
=> Fix: 팔로우모달 흰 점 제거

README.md
`feature/README.md` -> `dev`
실행 화면은 gif 파일입니다! 추가적인 내용 필요하시면 말씀해주세요!
=> Docs: README.md 파일 작성

index.html
`feature/` -> `hotfix/metatag_build_error`
- 메타태그 오류 및 중복 수정
=> Hotfix : 메타태그 오타 및 중복 수정

.eslintrc.cjs, package-lock.json, package.json, src/Services/Post/index.ts, src/Services/User/index.ts, src/Utils/resizeImage.ts
- react-image-file-resizer를 통해 업로드 시 이미지 사이즈 최적화 및 파일 형식 webP로 포맷
- resizeImage 유틸 함수 기능 개발
- 이미지 업로드 관련 API에 적용
=> Feature: 이미지 업로드 최적화
